### PR TITLE
fix: error handling and add TS types Sebbe PR #280 with refactor

### LINKED ISSUE #256: useAsyncStoryblok result is not typed
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

useAsyncStoryblok result is not typed in any way and returns `any` as type
---
## Expected Behavior

I expect the result from `useAsyncStoryblok` to be properly typed like `useStoryblok`.
image
image

## Current Behavior
Compared to the composable `useStoryblok`, the composable `useAsyncStoryblok` does not have a typed result.
This means that eslint reports an error and worse development experience.
image
image

## Steps to Reproduce

1. Use the nuxt3 storyblok module in a nuxt3 project
2. Use the `useAsyncStoryblok` composable
3. Look at the return type for the result.

### PR DESCRIPTION
**Pull request by Dawntraoz**
- Adds typed return, typed state, and params by @SebbeJohansson #280 close #256
- Add error handling suggested at #267 
- Remove async await from the call (not needed at all)

### CODE REVIEW

**Comment by SebbeJohansson** [comment]
🕺

File: lib/src/runtime/composables/useAsyncStoryblok.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import { useStoryblokApi, useStoryblokBridge } from "@storyblok/vue";
+import type { ISbStoriesParams, StoryblokBridgeConfigV2, ISbStoryData, ISbError, ISbResult } from '@storyblok/vue';
+import { useAsyncData, useState, onMounted, createError } from "#imports";
+
+export const useAsyncStoryblok = async (
+  url: string,
+  apiOptions: ISbStoriesParams = {},
```
Comment (alvarosabu) [inline lib/src/runtime/composables/useAsyncStoryblok.ts:7]: Hey @Dawntraoz, `apiOptions` and `bridgeOptions` have a default value because we need to pass them as empty below on the `storyblokApiInstance.get(`cdn/stories/${url}`, apiOptions)` and `useStoryblokBridge` respectively?

**Review by fgiuliani — APPROVED** [review]

File: lib/src/runtime/composables/useAsyncStoryblok.ts (hunk 1 above)
Comment (Dawntraoz) [reply lib/src/runtime/composables/useAsyncStoryblok.ts:7]: Well the bridge is already initializing the options to empty object here -> https://github.com/storyblok/storyblok-js/blob/main/lib/index.ts

**Review by alvarosabu — APPROVED** [review]
Looks good, nice work @Dawntraoz

**Comment by SebbeJohansson** [comment]
Glad we could figure out an amazing solution together 🥳

**Comment by Dawntraoz** [comment]
Such a nice community we are building @SebbeJohansson 💜
